Update .stderr files
ferrous-systems/testing-proc-macros pull request #2
Opened 2022-05-15 18:49 UTC by winksaville

With compiler 1.60.0:

  $ rustc --version
  rustc 1.60.0 (7737e0b5c 2022-04-04)

The contents of teh `.stderr` files is slightly different so the `.stderr`
files needed updating using `TRYBUILD=overwrite cargo test`.

Without this change I was getting errors like the following, with the
change the tests pass.
```
  test tests/ui/has-arguments.rs ... mismatch

  EXPECTED:
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  error: this attribute takes no arguments

    = help: use `#[contracts]`

   --> $DIR/has-arguments.rs:3:1
    |
  3 | #[contracts(a, b)]
    | ^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `contracts` (in Nightly builds, run with -Z macro-backtrace for more info)
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  ACTUAL OUTPUT:
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  error: this attribute takes no arguments

           = help: use `#[contracts]`

   --> tests/ui/has-arguments.rs:3:1
    |
  3 | #[contracts(a, b)]
    | ^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `contracts` (in Nightly builds, run with -Z macro-backtrace for more info)
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  note: If the actual output is the correct output you can bless it by rerunning
        your test with the environment variable TRYBUILD=overwrite

  test tests/ui/has-expr-argument.rs ... mismatch
```

2022-05-16 10:13 UTC, japaric requested changes
thanks for the PR. the `$DIR` should be preserved as it will match the directory name of the tests even if it changes. btw, running `TRYBUILD=overwrite cargo test` will update the `.stderr` files preserving the `$DIR` part.

2022-05-16 10:46 UTC, winksaville commented
Hmmm, I did use `TRYBUILD=overwrite cargo test`. I'll try again and if unsuccessful will manually change it. I'm on an Arch Linux system running rust 1.60.0.

2022-05-16 11:19 UTC, japaric commented
> One other thing that was odd, I couldn't use Visual Studio Code in that repo, it started but "hung" with a blank window, is that expected?

I don't see any issue with vs code 1.67.1 and rust-analyzer 0.3.1051 using revision 60a36e1 . it may be an issue with your vs code setup; maybe try other Rust projects and see if they run into the same issue.

2022-05-16 16:29 UTC, winksaville commented
I've forced push the change after manually changing the path to $DIR/... not sure why it changes for me :(

Also, I booted my desktop computer installed the latest vs code, previously I had 1.67.1-1 now I have 1.67.1-2 from commit da15b6f and 2022-05-06. I then cd to my fork of your repo on my branch and ran `code .`, worked like a charm. I then checked my rust-analyzer and have I the same as you v0.3.1051.

So, maybe it was 1.67.1-2 vs 1.67.1-1 but my guess having rebooted my system "fixed" something.

Anyway, on the vs code front all is well and the tests are working for me :)

```
wink@3900x 22-05-16T16:24:46.538Z:~/prgs/rust/myrepos/ferrous-systems-testing-proc-macros (Update-stderr-files)
$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests (target/debug/deps/contracts-ba10f924ddbf31e0)

running 5 tests
test lower::tests::produces_assertion_for_precondition ... ok
test analyze::tests::can_extract_precondition ... ok
test analyze::tests::non_dsl_attributes_are_preserved ... ok
test codegen::tests::output_is_function_item ... ok
test parse::tests::valid_syntax ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/precondition.rs (target/debug/deps/precondition-7e5da3776f7abacd)

running 2 tests
test fail - should panic ... ok
test pass ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/ui.rs (target/debug/deps/ui-b0c3547267355bbf)

running 1 test
    Checking contracts-tests v0.0.0 (/home/wink/prgs/rust/myrepos/ferrous-systems-testing-proc-macros/target/tests/contracts)
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s


test tests/ui/has-arguments.rs ... ok
test tests/ui/has-expr-argument.rs ... ok
test tests/ui/item-is-not-a-function.rs ... ok
test tests/ui/precondition-is-not-an-expression.rs ... ok
test tests/ui/zero-contracts.rs ... ok


test ui ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.56s

   Doc-tests contracts

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

2022-05-17 09:31 UTC, japaric approved these changes
Thanks!

2022-05-17 09:31 UTC, merged